// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "jacobi_HLS.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic jacobi_HLS::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic jacobi_HLS::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state1 = "1";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state2 = "10";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state3 = "100";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state4 = "1000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state5 = "10000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state6 = "100000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state7 = "1000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state8 = "10000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state9 = "100000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state10 = "1000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state11 = "10000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state12 = "100000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state55 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state56 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state57 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state58 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state59 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state60 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state61 = "1000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state62 = "10000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state63 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state64 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state65 = "10000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state66 = "100000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state67 = "1000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state68 = "10000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state69 = "100000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state70 = "1000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state71 = "10000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state72 = "100000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state73 = "1000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state74 = "10000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state75 = "100000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state76 = "1000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state77 = "10000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state78 = "100000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state79 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state80 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state81 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state82 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state83 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state84 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state85 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state86 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state87 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state88 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state89 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state90 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state91 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state92 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state93 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state94 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state95 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state96 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state97 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state98 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state99 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state100 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state101 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state102 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state103 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state104 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state105 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state106 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state107 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state108 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state109 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state110 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state111 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state112 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state113 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<114> jacobi_HLS::ap_ST_fsm_state114 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> jacobi_HLS::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> jacobi_HLS::ap_const_lv32_C = "1100";
const sc_lv<32> jacobi_HLS::ap_const_lv32_19 = "11001";
const sc_lv<32> jacobi_HLS::ap_const_lv32_1E = "11110";
const sc_lv<32> jacobi_HLS::ap_const_lv32_4E = "1001110";
const sc_lv<32> jacobi_HLS::ap_const_lv32_12 = "10010";
const sc_lv<1> jacobi_HLS::ap_const_lv1_1 = "1";
const sc_lv<32> jacobi_HLS::ap_const_lv32_53 = "1010011";
const sc_lv<32> jacobi_HLS::ap_const_lv32_1 = "1";
const sc_lv<32> jacobi_HLS::ap_const_lv32_2 = "10";
const sc_lv<32> jacobi_HLS::ap_const_lv32_4 = "100";
const sc_lv<1> jacobi_HLS::ap_const_lv1_0 = "0";
const sc_lv<32> jacobi_HLS::ap_const_lv32_5 = "101";
const sc_lv<32> jacobi_HLS::ap_const_lv32_6 = "110";
const sc_lv<32> jacobi_HLS::ap_const_lv32_D = "1101";
const sc_lv<32> jacobi_HLS::ap_const_lv32_13 = "10011";
const sc_lv<32> jacobi_HLS::ap_const_lv32_14 = "10100";
const sc_lv<32> jacobi_HLS::ap_const_lv32_24 = "100100";
const sc_lv<32> jacobi_HLS::ap_const_lv32_43 = "1000011";
const sc_lv<32> jacobi_HLS::ap_const_lv32_44 = "1000100";
const sc_lv<32> jacobi_HLS::ap_const_lv32_46 = "1000110";
const sc_lv<32> jacobi_HLS::ap_const_lv32_47 = "1000111";
const sc_lv<32> jacobi_HLS::ap_const_lv32_48 = "1001000";
const sc_lv<5> jacobi_HLS::ap_const_lv5_0 = "00000";
const sc_lv<3> jacobi_HLS::ap_const_lv3_0 = "000";
const sc_lv<32> jacobi_HLS::ap_const_lv32_3 = "11";
const sc_lv<32> jacobi_HLS::ap_const_lv32_45 = "1000101";
const sc_lv<64> jacobi_HLS::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> jacobi_HLS::ap_const_lv64_10 = "10000";
const sc_lv<32> jacobi_HLS::ap_const_lv32_E = "1110";
const sc_lv<32> jacobi_HLS::ap_const_lv32_1A = "11010";
const sc_lv<32> jacobi_HLS::ap_const_lv32_4F = "1001111";
const sc_lv<32> jacobi_HLS::ap_const_lv32_1F = "11111";
const sc_lv<64> jacobi_HLS::ap_const_lv64_3FF0000000000000 = "11111111110000000000000000000000000000000000000000000000000000";
const sc_lv<32> jacobi_HLS::ap_const_lv32_25 = "100101";
const sc_lv<32> jacobi_HLS::ap_const_lv32_7 = "111";
const sc_lv<32> jacobi_HLS::ap_const_lv32_49 = "1001001";
const sc_lv<5> jacobi_HLS::ap_const_lv5_10 = "10000";
const sc_lv<5> jacobi_HLS::ap_const_lv5_1 = "1";
const sc_lv<3> jacobi_HLS::ap_const_lv3_4 = "100";
const sc_lv<3> jacobi_HLS::ap_const_lv3_1 = "1";
const sc_lv<3> jacobi_HLS::ap_const_lv3_7 = "111";
const sc_lv<2> jacobi_HLS::ap_const_lv2_0 = "00";
const sc_lv<32> jacobi_HLS::ap_const_lv32_3F = "111111";
const sc_lv<32> jacobi_HLS::ap_const_lv32_34 = "110100";
const sc_lv<32> jacobi_HLS::ap_const_lv32_3E = "111110";
const sc_lv<12> jacobi_HLS::ap_const_lv12_C01 = "110000000001";
const sc_lv<32> jacobi_HLS::ap_const_lv32_B = "1011";
const sc_lv<11> jacobi_HLS::ap_const_lv11_3FF = "1111111111";
const sc_lv<32> jacobi_HLS::ap_const_lv32_35 = "110101";
const sc_lv<32> jacobi_HLS::ap_const_lv32_54 = "1010100";
const sc_lv<2> jacobi_HLS::ap_const_lv2_1 = "1";
const sc_lv<32> jacobi_HLS::ap_const_lv32_71 = "1110001";
const bool jacobi_HLS::ap_const_boolean_1 = true;

jacobi_HLS::jacobi_HLS(sc_module_name name) : sc_module(name), mVcdFile(0) {
    x_prev_U = new jacobi_HLS_x_prev("x_prev_U");
    x_prev_U->clk(ap_clk);
    x_prev_U->reset(ap_rst);
    x_prev_U->address0(x_prev_address0);
    x_prev_U->ce0(x_prev_ce0);
    x_prev_U->we0(x_prev_we0);
    x_prev_U->d0(x_prev_d0);
    x_prev_U->q0(x_prev_q0);
    x_new_U = new jacobi_HLS_x_prev("x_new_U");
    x_new_U->clk(ap_clk);
    x_new_U->reset(ap_rst);
    x_new_U->address0(x_new_address0);
    x_new_U->ce0(x_new_ce0);
    x_new_U->we0(x_new_we0);
    x_new_U->d0(x_new_d0);
    x_new_U->q0(x_new_q0);
    jacobi_HLS_dadddsbkb_U1 = new jacobi_HLS_dadddsbkb<1,5,64,64,64>("jacobi_HLS_dadddsbkb_U1");
    jacobi_HLS_dadddsbkb_U1->clk(ap_clk);
    jacobi_HLS_dadddsbkb_U1->reset(ap_rst);
    jacobi_HLS_dadddsbkb_U1->din0(grp_fu_295_p0);
    jacobi_HLS_dadddsbkb_U1->din1(grp_fu_295_p1);
    jacobi_HLS_dadddsbkb_U1->opcode(grp_fu_295_opcode);
    jacobi_HLS_dadddsbkb_U1->ce(ap_var_for_const0);
    jacobi_HLS_dadddsbkb_U1->dout(grp_fu_295_p2);
    jacobi_HLS_dmul_6cud_U2 = new jacobi_HLS_dmul_6cud<1,6,64,64,64>("jacobi_HLS_dmul_6cud_U2");
    jacobi_HLS_dmul_6cud_U2->clk(ap_clk);
    jacobi_HLS_dmul_6cud_U2->reset(ap_rst);
    jacobi_HLS_dmul_6cud_U2->din0(reg_321);
    jacobi_HLS_dmul_6cud_U2->din1(reg_328);
    jacobi_HLS_dmul_6cud_U2->ce(ap_var_for_const0);
    jacobi_HLS_dmul_6cud_U2->dout(grp_fu_302_p2);
    jacobi_HLS_ddiv_6dEe_U3 = new jacobi_HLS_ddiv_6dEe<1,31,64,64,64>("jacobi_HLS_ddiv_6dEe_U3");
    jacobi_HLS_ddiv_6dEe_U3->clk(ap_clk);
    jacobi_HLS_ddiv_6dEe_U3->reset(ap_rst);
    jacobi_HLS_ddiv_6dEe_U3->din0(ap_var_for_const1);
    jacobi_HLS_ddiv_6dEe_U3->din1(tmp_10_reg_706);
    jacobi_HLS_ddiv_6dEe_U3->ce(ap_var_for_const0);
    jacobi_HLS_ddiv_6dEe_U3->dout(grp_fu_306_p2);
    jacobi_HLS_sitodpeOg_U4 = new jacobi_HLS_sitodpeOg<1,6,32,64>("jacobi_HLS_sitodpeOg_U4");
    jacobi_HLS_sitodpeOg_U4->clk(ap_clk);
    jacobi_HLS_sitodpeOg_U4->reset(ap_rst);
    jacobi_HLS_sitodpeOg_U4->din0(grp_fu_311_p0);
    jacobi_HLS_sitodpeOg_U4->ce(ap_var_for_const0);
    jacobi_HLS_sitodpeOg_U4->dout(grp_fu_311_p1);
    jacobi_HLS_dsqrt_fYi_U5 = new jacobi_HLS_dsqrt_fYi<1,31,64,64,64>("jacobi_HLS_dsqrt_fYi_U5");
    jacobi_HLS_dsqrt_fYi_U5->clk(ap_clk);
    jacobi_HLS_dsqrt_fYi_U5->reset(ap_rst);
    jacobi_HLS_dsqrt_fYi_U5->din0(ap_var_for_const2);
    jacobi_HLS_dsqrt_fYi_U5->din1(sum_reg_272);
    jacobi_HLS_dsqrt_fYi_U5->ce(ap_var_for_const0);
    jacobi_HLS_dsqrt_fYi_U5->dout(grp_fu_315_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_J_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_17_cast_fu_409_p1 );

    SC_METHOD(thread_J_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state114);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state68);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state69);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state70);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state71);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state72);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state73);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state74);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state79);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state80);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state84);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state114 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state114 );

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_fu_315_p2 );
    sensitive << ( ap_CS_fsm_state114 );

    SC_METHOD(thread_b_address0);
    sensitive << ( tmp_12_reg_646 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_b_ce0);
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_exitcond1_fu_418_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( j_reg_261 );

    SC_METHOD(thread_exitcond2_fu_364_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_reg_237 );

    SC_METHOD(thread_exitcond3_fu_352_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( t_reg_226 );

    SC_METHOD(thread_exitcond4_fu_334_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_215 );

    SC_METHOD(thread_exitcond_fu_584_p2);
    sensitive << ( ap_CS_fsm_state71 );
    sensitive << ( q_reg_284 );

    SC_METHOD(thread_grp_fu_295_opcode);
    sensitive << ( tmp_13_reg_686 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state80 );

    SC_METHOD(thread_grp_fu_295_p0);
    sensitive << ( reg_321 );
    sensitive << ( sigma_reg_249 );
    sensitive << ( sum_reg_272 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state80 );

    SC_METHOD(thread_grp_fu_295_p1);
    sensitive << ( reg_321 );
    sensitive << ( sigma_reg_249 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state80 );

    SC_METHOD(thread_grp_fu_311_p0);
    sensitive << ( b_q0 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( J_load_reg_662 );
    sensitive << ( tmp_14_reg_673 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_4_reg_756 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state74 );

    SC_METHOD(thread_i_1_fu_340_p2);
    sensitive << ( i_reg_215 );

    SC_METHOD(thread_i_2_fu_370_p2);
    sensitive << ( i1_reg_237 );

    SC_METHOD(thread_isNeg_fu_492_p3);
    sensitive << ( sh_assign_fu_486_p2 );

    SC_METHOD(thread_j_1_fu_424_p2);
    sensitive << ( j_reg_261 );

    SC_METHOD(thread_mantissa_V_1_cast_fu_478_p1);
    sensitive << ( mantissa_V_fu_468_p4 );

    SC_METHOD(thread_mantissa_V_fu_468_p4);
    sensitive << ( tmp_V_1_fu_464_p1 );

    SC_METHOD(thread_p_Val2_5_fu_564_p3);
    sensitive << ( isNeg_fu_492_p3 );
    sensitive << ( tmp_17_fu_550_p1 );
    sensitive << ( tmp_18_fu_554_p4 );

    SC_METHOD(thread_p_Val2_6_fu_577_p3);
    sensitive << ( p_Result_s_reg_716 );
    sensitive << ( p_Val2_5_reg_721 );
    sensitive << ( result_V_1_fu_572_p2 );

    SC_METHOD(thread_p_Val2_s_fu_443_p1);
    sensitive << ( x_assign_reg_711 );

    SC_METHOD(thread_q_1_fu_590_p2);
    sensitive << ( q_reg_284 );

    SC_METHOD(thread_r_V_1_fu_536_p2);
    sensitive << ( mantissa_V_1_cast_fu_478_p1 );
    sensitive << ( tmp_i_i_i_10_fu_522_p1 );

    SC_METHOD(thread_r_V_fu_530_p2);
    sensitive << ( mantissa_V_fu_468_p4 );
    sensitive << ( tmp_i_i_i_cast_11_fu_526_p1 );

    SC_METHOD(thread_result_V_1_fu_572_p2);
    sensitive << ( p_Val2_5_reg_721 );

    SC_METHOD(thread_sh_assign_2_cast_fu_518_p1);
    sensitive << ( ush_fu_510_p3 );

    SC_METHOD(thread_sh_assign_fu_486_p2);
    sensitive << ( tmp_i_i_i_i_cast2_fu_482_p1 );

    SC_METHOD(thread_sigma_1_fu_436_p3);
    sensitive << ( reg_328 );
    sensitive << ( tmp_13_reg_686 );
    sensitive << ( sigma_reg_249 );

    SC_METHOD(thread_t_1_fu_358_p2);
    sensitive << ( t_reg_226 );

    SC_METHOD(thread_tmp_11_fu_382_p3);
    sensitive << ( tmp_9_fu_376_p2 );

    SC_METHOD(thread_tmp_12_cast_fu_399_p1);
    sensitive << ( i1_reg_237 );

    SC_METHOD(thread_tmp_12_fu_394_p1);
    sensitive << ( i1_reg_237 );

    SC_METHOD(thread_tmp_13_fu_430_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( exitcond1_fu_418_p2 );
    sensitive << ( i1_reg_237 );
    sensitive << ( j_reg_261 );

    SC_METHOD(thread_tmp_14_fu_414_p2);
    sensitive << ( J_load_reg_662 );
    sensitive << ( x_prev_load_1_reg_668 );

    SC_METHOD(thread_tmp_16_cast_fu_390_p1);
    sensitive << ( tmp_11_fu_382_p3 );

    SC_METHOD(thread_tmp_16_fu_403_p2);
    sensitive << ( tmp_12_cast_fu_399_p1 );
    sensitive << ( tmp_16_cast_fu_390_p1 );

    SC_METHOD(thread_tmp_17_cast_fu_409_p1);
    sensitive << ( tmp_16_fu_403_p2 );

    SC_METHOD(thread_tmp_17_fu_550_p1);
    sensitive << ( tmp_22_fu_542_p3 );

    SC_METHOD(thread_tmp_18_fu_554_p4);
    sensitive << ( r_V_1_fu_536_p2 );

    SC_METHOD(thread_tmp_22_fu_542_p3);
    sensitive << ( r_V_fu_530_p2 );

    SC_METHOD(thread_tmp_2_fu_596_p1);
    sensitive << ( q_reg_284 );

    SC_METHOD(thread_tmp_3_fu_602_p2);
    sensitive << ( x_prev_q0 );
    sensitive << ( x_new_q0 );

    SC_METHOD(thread_tmp_4_fu_608_p2);
    sensitive << ( tmp_3_reg_750 );

    SC_METHOD(thread_tmp_9_fu_376_p2);
    sensitive << ( i1_reg_237 );

    SC_METHOD(thread_tmp_V_1_fu_464_p1);
    sensitive << ( p_Val2_s_fu_443_p1 );

    SC_METHOD(thread_tmp_V_fu_454_p4);
    sensitive << ( p_Val2_s_fu_443_p1 );

    SC_METHOD(thread_tmp_fu_346_p1);
    sensitive << ( i_reg_215 );

    SC_METHOD(thread_tmp_i_i_i_10_fu_522_p1);
    sensitive << ( sh_assign_2_cast_fu_518_p1 );

    SC_METHOD(thread_tmp_i_i_i_cast_11_fu_526_p1);
    sensitive << ( sh_assign_2_cast_fu_518_p1 );

    SC_METHOD(thread_tmp_i_i_i_cast_fu_506_p1);
    sensitive << ( tmp_i_i_i_fu_500_p2 );

    SC_METHOD(thread_tmp_i_i_i_fu_500_p2);
    sensitive << ( tmp_V_fu_454_p4 );

    SC_METHOD(thread_tmp_i_i_i_i_cast2_fu_482_p1);
    sensitive << ( tmp_V_fu_454_p4 );

    SC_METHOD(thread_ush_fu_510_p3);
    sensitive << ( sh_assign_fu_486_p2 );
    sensitive << ( isNeg_fu_492_p3 );
    sensitive << ( tmp_i_i_i_cast_fu_506_p1 );

    SC_METHOD(thread_x_address0);
    sensitive << ( tmp_2_reg_735 );
    sensitive << ( ap_CS_fsm_state72 );

    SC_METHOD(thread_x_ce0);
    sensitive << ( ap_CS_fsm_state72 );

    SC_METHOD(thread_x_d0);
    sensitive << ( ap_CS_fsm_state72 );
    sensitive << ( x_new_q0 );

    SC_METHOD(thread_x_new_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_12_reg_646 );
    sensitive << ( ap_CS_fsm_state71 );
    sensitive << ( tmp_2_fu_596_p1 );
    sensitive << ( ap_CS_fsm_state70 );
    sensitive << ( tmp_fu_346_p1 );

    SC_METHOD(thread_x_new_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state71 );
    sensitive << ( ap_CS_fsm_state70 );

    SC_METHOD(thread_x_new_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state70 );
    sensitive << ( p_Val2_6_fu_577_p3 );

    SC_METHOD(thread_x_new_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond4_fu_334_p2 );
    sensitive << ( ap_CS_fsm_state70 );

    SC_METHOD(thread_x_prev_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_12_fu_394_p1 );
    sensitive << ( ap_CS_fsm_state71 );
    sensitive << ( tmp_2_fu_596_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_fu_346_p1 );

    SC_METHOD(thread_x_prev_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state71 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_x_prev_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( x_new_q0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_x_prev_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond4_fu_334_p2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_x_we0);
    sensitive << ( ap_CS_fsm_state72 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond4_fu_334_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond2_fu_364_p2 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( exitcond1_fu_418_p2 );
    sensitive << ( ap_CS_fsm_state71 );
    sensitive << ( exitcond_fu_584_p2 );
    sensitive << ( exitcond3_fu_352_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "jacobi_HLS_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, J_address0, "(port)J_address0");
    sc_trace(mVcdFile, J_ce0, "(port)J_ce0");
    sc_trace(mVcdFile, J_q0, "(port)J_q0");
    sc_trace(mVcdFile, b_address0, "(port)b_address0");
    sc_trace(mVcdFile, b_ce0, "(port)b_ce0");
    sc_trace(mVcdFile, b_q0, "(port)b_q0");
    sc_trace(mVcdFile, x_address0, "(port)x_address0");
    sc_trace(mVcdFile, x_ce0, "(port)x_ce0");
    sc_trace(mVcdFile, x_we0, "(port)x_we0");
    sc_trace(mVcdFile, x_d0, "(port)x_d0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_311_p1, "grp_fu_311_p1");
    sc_trace(mVcdFile, reg_321, "reg_321");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, ap_CS_fsm_state79, "ap_CS_fsm_state79");
    sc_trace(mVcdFile, grp_fu_295_p2, "grp_fu_295_p2");
    sc_trace(mVcdFile, reg_328, "reg_328");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, tmp_13_reg_686, "tmp_13_reg_686");
    sc_trace(mVcdFile, ap_CS_fsm_state84, "ap_CS_fsm_state84");
    sc_trace(mVcdFile, i_1_fu_340_p2, "i_1_fu_340_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond4_fu_334_p2, "exitcond4_fu_334_p2");
    sc_trace(mVcdFile, t_1_fu_358_p2, "t_1_fu_358_p2");
    sc_trace(mVcdFile, t_1_reg_633, "t_1_reg_633");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_2_fu_370_p2, "i_2_fu_370_p2");
    sc_trace(mVcdFile, i_2_reg_641, "i_2_reg_641");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_12_fu_394_p1, "tmp_12_fu_394_p1");
    sc_trace(mVcdFile, tmp_12_reg_646, "tmp_12_reg_646");
    sc_trace(mVcdFile, exitcond2_fu_364_p2, "exitcond2_fu_364_p2");
    sc_trace(mVcdFile, J_load_reg_662, "J_load_reg_662");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, x_prev_q0, "x_prev_q0");
    sc_trace(mVcdFile, x_prev_load_1_reg_668, "x_prev_load_1_reg_668");
    sc_trace(mVcdFile, tmp_14_fu_414_p2, "tmp_14_fu_414_p2");
    sc_trace(mVcdFile, tmp_14_reg_673, "tmp_14_reg_673");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, j_1_fu_424_p2, "j_1_fu_424_p2");
    sc_trace(mVcdFile, j_1_reg_681, "j_1_reg_681");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_13_fu_430_p2, "tmp_13_fu_430_p2");
    sc_trace(mVcdFile, exitcond1_fu_418_p2, "exitcond1_fu_418_p2");
    sc_trace(mVcdFile, sigma_1_fu_436_p3, "sigma_1_fu_436_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, grp_fu_302_p2, "grp_fu_302_p2");
    sc_trace(mVcdFile, tmp_10_reg_706, "tmp_10_reg_706");
    sc_trace(mVcdFile, ap_CS_fsm_state37, "ap_CS_fsm_state37");
    sc_trace(mVcdFile, grp_fu_306_p2, "grp_fu_306_p2");
    sc_trace(mVcdFile, x_assign_reg_711, "x_assign_reg_711");
    sc_trace(mVcdFile, ap_CS_fsm_state68, "ap_CS_fsm_state68");
    sc_trace(mVcdFile, p_Result_s_reg_716, "p_Result_s_reg_716");
    sc_trace(mVcdFile, ap_CS_fsm_state69, "ap_CS_fsm_state69");
    sc_trace(mVcdFile, p_Val2_5_fu_564_p3, "p_Val2_5_fu_564_p3");
    sc_trace(mVcdFile, p_Val2_5_reg_721, "p_Val2_5_reg_721");
    sc_trace(mVcdFile, q_1_fu_590_p2, "q_1_fu_590_p2");
    sc_trace(mVcdFile, q_1_reg_730, "q_1_reg_730");
    sc_trace(mVcdFile, ap_CS_fsm_state71, "ap_CS_fsm_state71");
    sc_trace(mVcdFile, tmp_2_fu_596_p1, "tmp_2_fu_596_p1");
    sc_trace(mVcdFile, tmp_2_reg_735, "tmp_2_reg_735");
    sc_trace(mVcdFile, exitcond_fu_584_p2, "exitcond_fu_584_p2");
    sc_trace(mVcdFile, tmp_3_fu_602_p2, "tmp_3_fu_602_p2");
    sc_trace(mVcdFile, tmp_3_reg_750, "tmp_3_reg_750");
    sc_trace(mVcdFile, ap_CS_fsm_state72, "ap_CS_fsm_state72");
    sc_trace(mVcdFile, tmp_4_fu_608_p2, "tmp_4_fu_608_p2");
    sc_trace(mVcdFile, tmp_4_reg_756, "tmp_4_reg_756");
    sc_trace(mVcdFile, ap_CS_fsm_state73, "ap_CS_fsm_state73");
    sc_trace(mVcdFile, x_prev_address0, "x_prev_address0");
    sc_trace(mVcdFile, x_prev_ce0, "x_prev_ce0");
    sc_trace(mVcdFile, x_prev_we0, "x_prev_we0");
    sc_trace(mVcdFile, x_prev_d0, "x_prev_d0");
    sc_trace(mVcdFile, x_new_address0, "x_new_address0");
    sc_trace(mVcdFile, x_new_ce0, "x_new_ce0");
    sc_trace(mVcdFile, x_new_we0, "x_new_we0");
    sc_trace(mVcdFile, x_new_d0, "x_new_d0");
    sc_trace(mVcdFile, x_new_q0, "x_new_q0");
    sc_trace(mVcdFile, i_reg_215, "i_reg_215");
    sc_trace(mVcdFile, t_reg_226, "t_reg_226");
    sc_trace(mVcdFile, i1_reg_237, "i1_reg_237");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state70, "ap_CS_fsm_state70");
    sc_trace(mVcdFile, sigma_reg_249, "sigma_reg_249");
    sc_trace(mVcdFile, j_reg_261, "j_reg_261");
    sc_trace(mVcdFile, sum_reg_272, "sum_reg_272");
    sc_trace(mVcdFile, exitcond3_fu_352_p2, "exitcond3_fu_352_p2");
    sc_trace(mVcdFile, q_reg_284, "q_reg_284");
    sc_trace(mVcdFile, tmp_fu_346_p1, "tmp_fu_346_p1");
    sc_trace(mVcdFile, tmp_17_cast_fu_409_p1, "tmp_17_cast_fu_409_p1");
    sc_trace(mVcdFile, p_Val2_6_fu_577_p3, "p_Val2_6_fu_577_p3");
    sc_trace(mVcdFile, grp_fu_295_p0, "grp_fu_295_p0");
    sc_trace(mVcdFile, grp_fu_295_p1, "grp_fu_295_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, ap_CS_fsm_state80, "ap_CS_fsm_state80");
    sc_trace(mVcdFile, ap_CS_fsm_state32, "ap_CS_fsm_state32");
    sc_trace(mVcdFile, ap_CS_fsm_state38, "ap_CS_fsm_state38");
    sc_trace(mVcdFile, grp_fu_311_p0, "grp_fu_311_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state74, "ap_CS_fsm_state74");
    sc_trace(mVcdFile, tmp_9_fu_376_p2, "tmp_9_fu_376_p2");
    sc_trace(mVcdFile, tmp_11_fu_382_p3, "tmp_11_fu_382_p3");
    sc_trace(mVcdFile, tmp_12_cast_fu_399_p1, "tmp_12_cast_fu_399_p1");
    sc_trace(mVcdFile, tmp_16_cast_fu_390_p1, "tmp_16_cast_fu_390_p1");
    sc_trace(mVcdFile, tmp_16_fu_403_p2, "tmp_16_fu_403_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_443_p1, "p_Val2_s_fu_443_p1");
    sc_trace(mVcdFile, tmp_V_1_fu_464_p1, "tmp_V_1_fu_464_p1");
    sc_trace(mVcdFile, mantissa_V_fu_468_p4, "mantissa_V_fu_468_p4");
    sc_trace(mVcdFile, tmp_V_fu_454_p4, "tmp_V_fu_454_p4");
    sc_trace(mVcdFile, tmp_i_i_i_i_cast2_fu_482_p1, "tmp_i_i_i_i_cast2_fu_482_p1");
    sc_trace(mVcdFile, sh_assign_fu_486_p2, "sh_assign_fu_486_p2");
    sc_trace(mVcdFile, tmp_i_i_i_fu_500_p2, "tmp_i_i_i_fu_500_p2");
    sc_trace(mVcdFile, isNeg_fu_492_p3, "isNeg_fu_492_p3");
    sc_trace(mVcdFile, tmp_i_i_i_cast_fu_506_p1, "tmp_i_i_i_cast_fu_506_p1");
    sc_trace(mVcdFile, ush_fu_510_p3, "ush_fu_510_p3");
    sc_trace(mVcdFile, sh_assign_2_cast_fu_518_p1, "sh_assign_2_cast_fu_518_p1");
    sc_trace(mVcdFile, tmp_i_i_i_cast_11_fu_526_p1, "tmp_i_i_i_cast_11_fu_526_p1");
    sc_trace(mVcdFile, mantissa_V_1_cast_fu_478_p1, "mantissa_V_1_cast_fu_478_p1");
    sc_trace(mVcdFile, tmp_i_i_i_10_fu_522_p1, "tmp_i_i_i_10_fu_522_p1");
    sc_trace(mVcdFile, r_V_fu_530_p2, "r_V_fu_530_p2");
    sc_trace(mVcdFile, tmp_22_fu_542_p3, "tmp_22_fu_542_p3");
    sc_trace(mVcdFile, r_V_1_fu_536_p2, "r_V_1_fu_536_p2");
    sc_trace(mVcdFile, tmp_17_fu_550_p1, "tmp_17_fu_550_p1");
    sc_trace(mVcdFile, tmp_18_fu_554_p4, "tmp_18_fu_554_p4");
    sc_trace(mVcdFile, result_V_1_fu_572_p2, "result_V_1_fu_572_p2");
    sc_trace(mVcdFile, grp_fu_295_opcode, "grp_fu_295_opcode");
    sc_trace(mVcdFile, grp_fu_315_p2, "grp_fu_315_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state114, "ap_CS_fsm_state114");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("jacobi_HLS.hdltvin.dat");
    mHdltvoutHandle.open("jacobi_HLS.hdltvout.dat");
}

jacobi_HLS::~jacobi_HLS() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete x_prev_U;
    delete x_new_U;
    delete jacobi_HLS_dadddsbkb_U1;
    delete jacobi_HLS_dmul_6cud_U2;
    delete jacobi_HLS_ddiv_6dEe_U3;
    delete jacobi_HLS_sitodpeOg_U4;
    delete jacobi_HLS_dsqrt_fYi_U5;
}

void jacobi_HLS::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void jacobi_HLS::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv64_0;
}

void jacobi_HLS::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_3FF0000000000000;
}

void jacobi_HLS::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state70.read())) {
        i1_reg_237 = i_2_reg_641.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i1_reg_237 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond4_fu_334_p2.read(), ap_const_lv1_0))) {
        i_reg_215 = i_1_fu_340_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_215 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        j_reg_261 = j_1_reg_681.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        j_reg_261 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_352_p2.read()))) {
        q_reg_284 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state84.read())) {
        q_reg_284 = q_1_reg_730.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        sigma_reg_249 = sigma_1_fu_436_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        sigma_reg_249 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_352_p2.read()))) {
        sum_reg_272 = ap_const_lv64_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state84.read())) {
        sum_reg_272 = grp_fu_295_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond4_fu_334_p2.read()))) {
        t_reg_226 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_364_p2.read()))) {
        t_reg_226 = t_1_reg_633.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        J_load_reg_662 = J_q0.read();
        x_prev_load_1_reg_668 = x_prev_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_2_reg_641 = i_2_fu_370_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        j_1_reg_681 = j_1_fu_424_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state69.read())) {
        p_Result_s_reg_716 = p_Val2_s_fu_443_p1.read().range(63, 63);
        p_Val2_5_reg_721 = p_Val2_5_fu_564_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state71.read())) {
        q_1_reg_730 = q_1_fu_590_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state79.read()))) {
        reg_321 = grp_fu_311_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && 
  esl_seteq<1,1,1>(tmp_13_reg_686.read(), ap_const_lv1_1)) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state84.read()))) {
        reg_328 = grp_fu_295_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        t_1_reg_633 = t_1_fu_358_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        tmp_10_reg_706 = grp_fu_302_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond2_fu_364_p2.read(), ap_const_lv1_0))) {
        tmp_12_reg_646 = tmp_12_fu_394_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_418_p2.read()))) {
        tmp_13_reg_686 = tmp_13_fu_430_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_14_reg_673 = tmp_14_fu_414_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state71.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_584_p2.read()))) {
        tmp_2_reg_735 = tmp_2_fu_596_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state72.read())) {
        tmp_3_reg_750 = tmp_3_fu_602_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state73.read())) {
        tmp_4_reg_756 = tmp_4_fu_608_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state68.read())) {
        x_assign_reg_711 = grp_fu_306_p2.read();
    }
}

void jacobi_HLS::thread_J_address0() {
    J_address0 =  (sc_lv<4>) (tmp_17_cast_fu_409_p1.read());
}

void jacobi_HLS::thread_J_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        J_ce0 = ap_const_logic_1;
    } else {
        J_ce0 = ap_const_logic_0;
    }
}

void jacobi_HLS::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void jacobi_HLS::thread_ap_CS_fsm_state114() {
    ap_CS_fsm_state114 = ap_CS_fsm.read()[113];
}

void jacobi_HLS::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void jacobi_HLS::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void jacobi_HLS::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void jacobi_HLS::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void jacobi_HLS::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void jacobi_HLS::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void jacobi_HLS::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void jacobi_HLS::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void jacobi_HLS::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void jacobi_HLS::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void jacobi_HLS::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read()[30];
}

void jacobi_HLS::thread_ap_CS_fsm_state32() {
    ap_CS_fsm_state32 = ap_CS_fsm.read()[31];
}

void jacobi_HLS::thread_ap_CS_fsm_state37() {
    ap_CS_fsm_state37 = ap_CS_fsm.read()[36];
}

void jacobi_HLS::thread_ap_CS_fsm_state38() {
    ap_CS_fsm_state38 = ap_CS_fsm.read()[37];
}

void jacobi_HLS::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void jacobi_HLS::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void jacobi_HLS::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void jacobi_HLS::thread_ap_CS_fsm_state68() {
    ap_CS_fsm_state68 = ap_CS_fsm.read()[67];
}

void jacobi_HLS::thread_ap_CS_fsm_state69() {
    ap_CS_fsm_state69 = ap_CS_fsm.read()[68];
}

void jacobi_HLS::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void jacobi_HLS::thread_ap_CS_fsm_state70() {
    ap_CS_fsm_state70 = ap_CS_fsm.read()[69];
}

void jacobi_HLS::thread_ap_CS_fsm_state71() {
    ap_CS_fsm_state71 = ap_CS_fsm.read()[70];
}

void jacobi_HLS::thread_ap_CS_fsm_state72() {
    ap_CS_fsm_state72 = ap_CS_fsm.read()[71];
}

void jacobi_HLS::thread_ap_CS_fsm_state73() {
    ap_CS_fsm_state73 = ap_CS_fsm.read()[72];
}

void jacobi_HLS::thread_ap_CS_fsm_state74() {
    ap_CS_fsm_state74 = ap_CS_fsm.read()[73];
}

void jacobi_HLS::thread_ap_CS_fsm_state79() {
    ap_CS_fsm_state79 = ap_CS_fsm.read()[78];
}

void jacobi_HLS::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void jacobi_HLS::thread_ap_CS_fsm_state80() {
    ap_CS_fsm_state80 = ap_CS_fsm.read()[79];
}

void jacobi_HLS::thread_ap_CS_fsm_state84() {
    ap_CS_fsm_state84 = ap_CS_fsm.read()[83];
}

void jacobi_HLS::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state114.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void jacobi_HLS::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void jacobi_HLS::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state114.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void jacobi_HLS::thread_ap_return() {
    ap_return = grp_fu_315_p2.read();
}

void jacobi_HLS::thread_b_address0() {
    b_address0 =  (sc_lv<2>) (tmp_12_reg_646.read());
}

void jacobi_HLS::thread_b_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        b_ce0 = ap_const_logic_1;
    } else {
        b_ce0 = ap_const_logic_0;
    }
}

void jacobi_HLS::thread_exitcond1_fu_418_p2() {
    exitcond1_fu_418_p2 = (!j_reg_261.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_261.read() == ap_const_lv3_4);
}

void jacobi_HLS::thread_exitcond2_fu_364_p2() {
    exitcond2_fu_364_p2 = (!i1_reg_237.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_237.read() == ap_const_lv3_4);
}

void jacobi_HLS::thread_exitcond3_fu_352_p2() {
    exitcond3_fu_352_p2 = (!t_reg_226.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(t_reg_226.read() == ap_const_lv5_10);
}

void jacobi_HLS::thread_exitcond4_fu_334_p2() {
    exitcond4_fu_334_p2 = (!i_reg_215.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_215.read() == ap_const_lv5_10);
}

void jacobi_HLS::thread_exitcond_fu_584_p2() {
    exitcond_fu_584_p2 = (!q_reg_284.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(q_reg_284.read() == ap_const_lv5_10);
}

void jacobi_HLS::thread_grp_fu_295_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        grp_fu_295_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state80.read()) || 
                (esl_seteq<1,1,1>(tmp_13_reg_686.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())))) {
        grp_fu_295_opcode = ap_const_lv2_0;
    } else {
        grp_fu_295_opcode = "XX";
    }
}

void jacobi_HLS::thread_grp_fu_295_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state80.read())) {
        grp_fu_295_p0 = sum_reg_272.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        grp_fu_295_p0 = reg_321.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        grp_fu_295_p0 = sigma_reg_249.read();
    } else {
        grp_fu_295_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void jacobi_HLS::thread_grp_fu_295_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        grp_fu_295_p1 = sigma_reg_249.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state80.read()))) {
        grp_fu_295_p1 = reg_321.read();
    } else {
        grp_fu_295_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void jacobi_HLS::thread_grp_fu_311_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state74.read())) {
        grp_fu_311_p0 = tmp_4_reg_756.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        grp_fu_311_p0 = J_load_reg_662.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        grp_fu_311_p0 = b_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        grp_fu_311_p0 = tmp_14_reg_673.read();
    } else {
        grp_fu_311_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void jacobi_HLS::thread_i_1_fu_340_p2() {
    i_1_fu_340_p2 = (!i_reg_215.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_215.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void jacobi_HLS::thread_i_2_fu_370_p2() {
    i_2_fu_370_p2 = (!i1_reg_237.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i1_reg_237.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void jacobi_HLS::thread_isNeg_fu_492_p3() {
    isNeg_fu_492_p3 = sh_assign_fu_486_p2.read().range(11, 11);
}

void jacobi_HLS::thread_j_1_fu_424_p2() {
    j_1_fu_424_p2 = (!j_reg_261.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j_reg_261.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void jacobi_HLS::thread_mantissa_V_1_cast_fu_478_p1() {
    mantissa_V_1_cast_fu_478_p1 = esl_zext<137,54>(mantissa_V_fu_468_p4.read());
}

void jacobi_HLS::thread_mantissa_V_fu_468_p4() {
    mantissa_V_fu_468_p4 = esl_concat<53,1>(esl_concat<1,52>(ap_const_lv1_1, tmp_V_1_fu_464_p1.read()), ap_const_lv1_0);
}

void jacobi_HLS::thread_p_Val2_5_fu_564_p3() {
    p_Val2_5_fu_564_p3 = (!isNeg_fu_492_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_fu_492_p3.read()[0].to_bool())? tmp_17_fu_550_p1.read(): tmp_18_fu_554_p4.read());
}

void jacobi_HLS::thread_p_Val2_6_fu_577_p3() {
    p_Val2_6_fu_577_p3 = (!p_Result_s_reg_716.read()[0].is_01())? sc_lv<32>(): ((p_Result_s_reg_716.read()[0].to_bool())? result_V_1_fu_572_p2.read(): p_Val2_5_reg_721.read());
}

void jacobi_HLS::thread_p_Val2_s_fu_443_p1() {
    p_Val2_s_fu_443_p1 = x_assign_reg_711.read();
}

void jacobi_HLS::thread_q_1_fu_590_p2() {
    q_1_fu_590_p2 = (!q_reg_284.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(q_reg_284.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void jacobi_HLS::thread_r_V_1_fu_536_p2() {
    r_V_1_fu_536_p2 = (!tmp_i_i_i_10_fu_522_p1.read().is_01())? sc_lv<137>(): mantissa_V_1_cast_fu_478_p1.read() << (unsigned short)tmp_i_i_i_10_fu_522_p1.read().to_uint();
}

void jacobi_HLS::thread_r_V_fu_530_p2() {
    r_V_fu_530_p2 = (!tmp_i_i_i_cast_11_fu_526_p1.read().is_01())? sc_lv<54>(): mantissa_V_fu_468_p4.read() >> (unsigned short)tmp_i_i_i_cast_11_fu_526_p1.read().to_uint();
}

void jacobi_HLS::thread_result_V_1_fu_572_p2() {
    result_V_1_fu_572_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_5_reg_721.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_5_reg_721.read()));
}

void jacobi_HLS::thread_sh_assign_2_cast_fu_518_p1() {
    sh_assign_2_cast_fu_518_p1 = esl_sext<32,12>(ush_fu_510_p3.read());
}

void jacobi_HLS::thread_sh_assign_fu_486_p2() {
    sh_assign_fu_486_p2 = (!ap_const_lv12_C01.is_01() || !tmp_i_i_i_i_cast2_fu_482_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_C01) + sc_biguint<12>(tmp_i_i_i_i_cast2_fu_482_p1.read()));
}

void jacobi_HLS::thread_sigma_1_fu_436_p3() {
    sigma_1_fu_436_p3 = (!tmp_13_reg_686.read()[0].is_01())? sc_lv<64>(): ((tmp_13_reg_686.read()[0].to_bool())? reg_328.read(): sigma_reg_249.read());
}

void jacobi_HLS::thread_t_1_fu_358_p2() {
    t_1_fu_358_p2 = (!t_reg_226.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(t_reg_226.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void jacobi_HLS::thread_tmp_11_fu_382_p3() {
    tmp_11_fu_382_p3 = esl_concat<3,2>(tmp_9_fu_376_p2.read(), ap_const_lv2_0);
}

void jacobi_HLS::thread_tmp_12_cast_fu_399_p1() {
    tmp_12_cast_fu_399_p1 = esl_zext<6,3>(i1_reg_237.read());
}

void jacobi_HLS::thread_tmp_12_fu_394_p1() {
    tmp_12_fu_394_p1 = esl_zext<64,3>(i1_reg_237.read());
}

void jacobi_HLS::thread_tmp_13_fu_430_p2() {
    tmp_13_fu_430_p2 = (!j_reg_261.read().is_01() || !i1_reg_237.read().is_01())? sc_lv<1>(): sc_lv<1>(j_reg_261.read() == i1_reg_237.read());
}

void jacobi_HLS::thread_tmp_14_fu_414_p2() {
    tmp_14_fu_414_p2 = (!J_load_reg_662.read().is_01() || !x_prev_load_1_reg_668.read().is_01())? sc_lv<32>(): sc_bigint<32>(J_load_reg_662.read()) * sc_bigint<32>(x_prev_load_1_reg_668.read());
}

void jacobi_HLS::thread_tmp_16_cast_fu_390_p1() {
    tmp_16_cast_fu_390_p1 = esl_sext<6,5>(tmp_11_fu_382_p3.read());
}

void jacobi_HLS::thread_tmp_16_fu_403_p2() {
    tmp_16_fu_403_p2 = (!tmp_12_cast_fu_399_p1.read().is_01() || !tmp_16_cast_fu_390_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_12_cast_fu_399_p1.read()) + sc_bigint<6>(tmp_16_cast_fu_390_p1.read()));
}

void jacobi_HLS::thread_tmp_17_cast_fu_409_p1() {
    tmp_17_cast_fu_409_p1 = esl_sext<64,6>(tmp_16_fu_403_p2.read());
}

void jacobi_HLS::thread_tmp_17_fu_550_p1() {
    tmp_17_fu_550_p1 = esl_zext<32,1>(tmp_22_fu_542_p3.read());
}

void jacobi_HLS::thread_tmp_18_fu_554_p4() {
    tmp_18_fu_554_p4 = r_V_1_fu_536_p2.read().range(84, 53);
}

void jacobi_HLS::thread_tmp_22_fu_542_p3() {
    tmp_22_fu_542_p3 = r_V_fu_530_p2.read().range(53, 53);
}

void jacobi_HLS::thread_tmp_2_fu_596_p1() {
    tmp_2_fu_596_p1 = esl_zext<64,5>(q_reg_284.read());
}

void jacobi_HLS::thread_tmp_3_fu_602_p2() {
    tmp_3_fu_602_p2 = (!x_new_q0.read().is_01() || !x_prev_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(x_new_q0.read()) - sc_biguint<32>(x_prev_q0.read()));
}

void jacobi_HLS::thread_tmp_4_fu_608_p2() {
    tmp_4_fu_608_p2 = (!tmp_3_reg_750.read().is_01() || !tmp_3_reg_750.read().is_01())? sc_lv<32>(): sc_bigint<32>(tmp_3_reg_750.read()) * sc_bigint<32>(tmp_3_reg_750.read());
}

void jacobi_HLS::thread_tmp_9_fu_376_p2() {
    tmp_9_fu_376_p2 = (!i1_reg_237.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<3>(): (sc_biguint<3>(i1_reg_237.read()) + sc_bigint<3>(ap_const_lv3_7));
}

void jacobi_HLS::thread_tmp_V_1_fu_464_p1() {
    tmp_V_1_fu_464_p1 = p_Val2_s_fu_443_p1.read().range(52-1, 0);
}

void jacobi_HLS::thread_tmp_V_fu_454_p4() {
    tmp_V_fu_454_p4 = p_Val2_s_fu_443_p1.read().range(62, 52);
}

void jacobi_HLS::thread_tmp_fu_346_p1() {
    tmp_fu_346_p1 = esl_zext<64,5>(i_reg_215.read());
}

void jacobi_HLS::thread_tmp_i_i_i_10_fu_522_p1() {
    tmp_i_i_i_10_fu_522_p1 = esl_zext<137,32>(sh_assign_2_cast_fu_518_p1.read());
}

void jacobi_HLS::thread_tmp_i_i_i_cast_11_fu_526_p1() {
    tmp_i_i_i_cast_11_fu_526_p1 = esl_zext<54,32>(sh_assign_2_cast_fu_518_p1.read());
}

void jacobi_HLS::thread_tmp_i_i_i_cast_fu_506_p1() {
    tmp_i_i_i_cast_fu_506_p1 = esl_sext<12,11>(tmp_i_i_i_fu_500_p2.read());
}

void jacobi_HLS::thread_tmp_i_i_i_fu_500_p2() {
    tmp_i_i_i_fu_500_p2 = (!ap_const_lv11_3FF.is_01() || !tmp_V_fu_454_p4.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_3FF) - sc_biguint<11>(tmp_V_fu_454_p4.read()));
}

void jacobi_HLS::thread_tmp_i_i_i_i_cast2_fu_482_p1() {
    tmp_i_i_i_i_cast2_fu_482_p1 = esl_zext<12,11>(tmp_V_fu_454_p4.read());
}

void jacobi_HLS::thread_ush_fu_510_p3() {
    ush_fu_510_p3 = (!isNeg_fu_492_p3.read()[0].is_01())? sc_lv<12>(): ((isNeg_fu_492_p3.read()[0].to_bool())? tmp_i_i_i_cast_fu_506_p1.read(): sh_assign_fu_486_p2.read());
}

void jacobi_HLS::thread_x_address0() {
    x_address0 =  (sc_lv<4>) (tmp_2_reg_735.read());
}

void jacobi_HLS::thread_x_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state72.read())) {
        x_ce0 = ap_const_logic_1;
    } else {
        x_ce0 = ap_const_logic_0;
    }
}

void jacobi_HLS::thread_x_d0() {
    x_d0 = x_new_q0.read();
}

void jacobi_HLS::thread_x_new_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state71.read())) {
        x_new_address0 =  (sc_lv<4>) (tmp_2_fu_596_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state70.read())) {
        x_new_address0 =  (sc_lv<4>) (tmp_12_reg_646.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        x_new_address0 =  (sc_lv<4>) (ap_const_lv64_10);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_new_address0 =  (sc_lv<4>) (tmp_fu_346_p1.read());
    } else {
        x_new_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void jacobi_HLS::thread_x_new_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state71.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state70.read()))) {
        x_new_ce0 = ap_const_logic_1;
    } else {
        x_new_ce0 = ap_const_logic_0;
    }
}

void jacobi_HLS::thread_x_new_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state70.read())) {
        x_new_d0 = p_Val2_6_fu_577_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_new_d0 = ap_const_lv32_1;
    } else {
        x_new_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void jacobi_HLS::thread_x_new_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond4_fu_334_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state70.read()))) {
        x_new_we0 = ap_const_logic_1;
    } else {
        x_new_we0 = ap_const_logic_0;
    }
}

void jacobi_HLS::thread_x_prev_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state71.read())) {
        x_prev_address0 =  (sc_lv<4>) (tmp_2_fu_596_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        x_prev_address0 =  (sc_lv<4>) (tmp_12_fu_394_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_prev_address0 =  (sc_lv<4>) (ap_const_lv64_10);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_prev_address0 =  (sc_lv<4>) (tmp_fu_346_p1.read());
    } else {
        x_prev_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void jacobi_HLS::thread_x_prev_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state71.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        x_prev_ce0 = ap_const_logic_1;
    } else {
        x_prev_ce0 = ap_const_logic_0;
    }
}

void jacobi_HLS::thread_x_prev_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_prev_d0 = x_new_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_prev_d0 = ap_const_lv32_0;
    } else {
        x_prev_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void jacobi_HLS::thread_x_prev_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond4_fu_334_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        x_prev_we0 = ap_const_logic_1;
    } else {
        x_prev_we0 = ap_const_logic_0;
    }
}

void jacobi_HLS::thread_x_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state72.read())) {
        x_we0 = ap_const_logic_1;
    } else {
        x_we0 = ap_const_logic_0;
    }
}

void jacobi_HLS::thread_ap_NS_fsm() {
    if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state1))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_NS_fsm = ap_ST_fsm_state2;
        } else {
            ap_NS_fsm = ap_ST_fsm_state1;
        }
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state2))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond4_fu_334_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state3;
        } else {
            ap_NS_fsm = ap_ST_fsm_state2;
        }
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state3))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_352_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state71;
        } else {
            ap_NS_fsm = ap_ST_fsm_state4;
        }
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state4))
    {
        ap_NS_fsm = ap_ST_fsm_state5;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state5))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_364_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state3;
        } else {
            ap_NS_fsm = ap_ST_fsm_state6;
        }
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state6))
    {
        ap_NS_fsm = ap_ST_fsm_state7;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state7))
    {
        ap_NS_fsm = ap_ST_fsm_state8;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state8))
    {
        ap_NS_fsm = ap_ST_fsm_state9;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state9))
    {
        ap_NS_fsm = ap_ST_fsm_state10;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state10))
    {
        ap_NS_fsm = ap_ST_fsm_state11;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state11))
    {
        ap_NS_fsm = ap_ST_fsm_state12;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state12))
    {
        ap_NS_fsm = ap_ST_fsm_state13;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state13))
    {
        ap_NS_fsm = ap_ST_fsm_state14;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state14))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_418_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state21;
        } else {
            ap_NS_fsm = ap_ST_fsm_state15;
        }
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state15))
    {
        ap_NS_fsm = ap_ST_fsm_state16;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state16))
    {
        ap_NS_fsm = ap_ST_fsm_state17;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state17))
    {
        ap_NS_fsm = ap_ST_fsm_state18;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state18))
    {
        ap_NS_fsm = ap_ST_fsm_state19;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state19))
    {
        ap_NS_fsm = ap_ST_fsm_state20;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state20))
    {
        ap_NS_fsm = ap_ST_fsm_state14;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state21))
    {
        ap_NS_fsm = ap_ST_fsm_state22;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state22))
    {
        ap_NS_fsm = ap_ST_fsm_state23;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state23))
    {
        ap_NS_fsm = ap_ST_fsm_state24;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state24))
    {
        ap_NS_fsm = ap_ST_fsm_state25;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state25))
    {
        ap_NS_fsm = ap_ST_fsm_state26;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state26))
    {
        ap_NS_fsm = ap_ST_fsm_state27;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state27))
    {
        ap_NS_fsm = ap_ST_fsm_state28;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state28))
    {
        ap_NS_fsm = ap_ST_fsm_state29;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state29))
    {
        ap_NS_fsm = ap_ST_fsm_state30;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state30))
    {
        ap_NS_fsm = ap_ST_fsm_state31;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state31))
    {
        ap_NS_fsm = ap_ST_fsm_state32;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state32))
    {
        ap_NS_fsm = ap_ST_fsm_state33;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state33))
    {
        ap_NS_fsm = ap_ST_fsm_state34;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state34))
    {
        ap_NS_fsm = ap_ST_fsm_state35;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state35))
    {
        ap_NS_fsm = ap_ST_fsm_state36;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state36))
    {
        ap_NS_fsm = ap_ST_fsm_state37;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state37))
    {
        ap_NS_fsm = ap_ST_fsm_state38;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state38))
    {
        ap_NS_fsm = ap_ST_fsm_state39;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state39))
    {
        ap_NS_fsm = ap_ST_fsm_state40;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state40))
    {
        ap_NS_fsm = ap_ST_fsm_state41;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state41))
    {
        ap_NS_fsm = ap_ST_fsm_state42;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state42))
    {
        ap_NS_fsm = ap_ST_fsm_state43;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state43))
    {
        ap_NS_fsm = ap_ST_fsm_state44;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state44))
    {
        ap_NS_fsm = ap_ST_fsm_state45;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state45))
    {
        ap_NS_fsm = ap_ST_fsm_state46;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state46))
    {
        ap_NS_fsm = ap_ST_fsm_state47;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state47))
    {
        ap_NS_fsm = ap_ST_fsm_state48;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state48))
    {
        ap_NS_fsm = ap_ST_fsm_state49;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state49))
    {
        ap_NS_fsm = ap_ST_fsm_state50;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state50))
    {
        ap_NS_fsm = ap_ST_fsm_state51;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state51))
    {
        ap_NS_fsm = ap_ST_fsm_state52;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state52))
    {
        ap_NS_fsm = ap_ST_fsm_state53;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state53))
    {
        ap_NS_fsm = ap_ST_fsm_state54;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state54))
    {
        ap_NS_fsm = ap_ST_fsm_state55;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state55))
    {
        ap_NS_fsm = ap_ST_fsm_state56;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state56))
    {
        ap_NS_fsm = ap_ST_fsm_state57;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state57))
    {
        ap_NS_fsm = ap_ST_fsm_state58;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state58))
    {
        ap_NS_fsm = ap_ST_fsm_state59;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state59))
    {
        ap_NS_fsm = ap_ST_fsm_state60;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state60))
    {
        ap_NS_fsm = ap_ST_fsm_state61;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state61))
    {
        ap_NS_fsm = ap_ST_fsm_state62;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state62))
    {
        ap_NS_fsm = ap_ST_fsm_state63;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state63))
    {
        ap_NS_fsm = ap_ST_fsm_state64;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state64))
    {
        ap_NS_fsm = ap_ST_fsm_state65;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state65))
    {
        ap_NS_fsm = ap_ST_fsm_state66;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state66))
    {
        ap_NS_fsm = ap_ST_fsm_state67;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state67))
    {
        ap_NS_fsm = ap_ST_fsm_state68;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state68))
    {
        ap_NS_fsm = ap_ST_fsm_state69;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state69))
    {
        ap_NS_fsm = ap_ST_fsm_state70;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state70))
    {
        ap_NS_fsm = ap_ST_fsm_state5;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state71))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state71.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_584_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state85;
        } else {
            ap_NS_fsm = ap_ST_fsm_state72;
        }
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state72))
    {
        ap_NS_fsm = ap_ST_fsm_state73;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state73))
    {
        ap_NS_fsm = ap_ST_fsm_state74;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state74))
    {
        ap_NS_fsm = ap_ST_fsm_state75;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state75))
    {
        ap_NS_fsm = ap_ST_fsm_state76;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state76))
    {
        ap_NS_fsm = ap_ST_fsm_state77;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state77))
    {
        ap_NS_fsm = ap_ST_fsm_state78;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state78))
    {
        ap_NS_fsm = ap_ST_fsm_state79;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state79))
    {
        ap_NS_fsm = ap_ST_fsm_state80;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state80))
    {
        ap_NS_fsm = ap_ST_fsm_state81;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state81))
    {
        ap_NS_fsm = ap_ST_fsm_state82;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state82))
    {
        ap_NS_fsm = ap_ST_fsm_state83;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state83))
    {
        ap_NS_fsm = ap_ST_fsm_state84;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state84))
    {
        ap_NS_fsm = ap_ST_fsm_state71;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state85))
    {
        ap_NS_fsm = ap_ST_fsm_state86;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state86))
    {
        ap_NS_fsm = ap_ST_fsm_state87;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state87))
    {
        ap_NS_fsm = ap_ST_fsm_state88;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state88))
    {
        ap_NS_fsm = ap_ST_fsm_state89;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state89))
    {
        ap_NS_fsm = ap_ST_fsm_state90;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state90))
    {
        ap_NS_fsm = ap_ST_fsm_state91;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state91))
    {
        ap_NS_fsm = ap_ST_fsm_state92;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state92))
    {
        ap_NS_fsm = ap_ST_fsm_state93;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state93))
    {
        ap_NS_fsm = ap_ST_fsm_state94;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state94))
    {
        ap_NS_fsm = ap_ST_fsm_state95;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state95))
    {
        ap_NS_fsm = ap_ST_fsm_state96;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state96))
    {
        ap_NS_fsm = ap_ST_fsm_state97;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state97))
    {
        ap_NS_fsm = ap_ST_fsm_state98;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state98))
    {
        ap_NS_fsm = ap_ST_fsm_state99;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state99))
    {
        ap_NS_fsm = ap_ST_fsm_state100;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state100))
    {
        ap_NS_fsm = ap_ST_fsm_state101;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state101))
    {
        ap_NS_fsm = ap_ST_fsm_state102;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state102))
    {
        ap_NS_fsm = ap_ST_fsm_state103;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state103))
    {
        ap_NS_fsm = ap_ST_fsm_state104;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state104))
    {
        ap_NS_fsm = ap_ST_fsm_state105;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state105))
    {
        ap_NS_fsm = ap_ST_fsm_state106;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state106))
    {
        ap_NS_fsm = ap_ST_fsm_state107;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state107))
    {
        ap_NS_fsm = ap_ST_fsm_state108;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state108))
    {
        ap_NS_fsm = ap_ST_fsm_state109;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state109))
    {
        ap_NS_fsm = ap_ST_fsm_state110;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state110))
    {
        ap_NS_fsm = ap_ST_fsm_state111;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state111))
    {
        ap_NS_fsm = ap_ST_fsm_state112;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state112))
    {
        ap_NS_fsm = ap_ST_fsm_state113;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state113))
    {
        ap_NS_fsm = ap_ST_fsm_state114;
    }
    else if (esl_seteq<1,114,114>(ap_CS_fsm.read(), ap_ST_fsm_state114))
    {
        ap_NS_fsm = ap_ST_fsm_state1;
    }
    else
    {
        ap_NS_fsm =  (sc_lv<114>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
void jacobi_HLS::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"J_address0\" :  \"" << J_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"J_ce0\" :  \"" << J_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"J_q0\" :  \"" << J_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_address0\" :  \"" << b_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_ce0\" :  \"" << b_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b_q0\" :  \"" << b_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"x_address0\" :  \"" << x_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"x_ce0\" :  \"" << x_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"x_we0\" :  \"" << x_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"x_d0\" :  \"" << x_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

